"""LLM-driven recommendation enrichment for health check reports (BL-034).

Hybrid approach:
  1. Rule-based _build_recommendations() runs first — fast, deterministic, high-confidence.
  2. LLMRecommender.enrich() appends cross-section insights the rule engine misses.

The LLM receives clean structured JSON (section names, severities, signal values vs
thresholds, key findings, existing recommendations). It never touches raw MongoDB output.
All data collection remains deterministic; only recommendation synthesis is LLM-driven.

Failure contract: any exception in enrich() is caught and logged; the existing
rule-based recommendations are returned unchanged so the health check never breaks.
"""
from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, List

from models.health_check_report import HealthCheckReport, Recommendation

if TYPE_CHECKING:
    from utils.config_loader import AppConfig

logger = logging.getLogger(__name__)

# ── system prompt ──────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """\
You are a senior MongoDB database reliability engineer reviewing a cluster health check.

You will receive a JSON health check report containing:
- sections: name, severity (ok/warning/critical), signals (measured values vs thresholds), key findings
- existing_recommendations: already generated by the rule engine (do NOT repeat these)

Your task: produce ADDITIONAL recommendations that the rule engine missed.

Focus on:
- Cross-section patterns (e.g. low cache hit ratio + high query targeting + full scans
  → the real problem is memory/working set, not just missing indexes)
- Operational signals in the Operations section: cache hit ratio, lock wait %, page faults,
  memory resident MB — these never produce rule-based recommendations today
- Replication risks: short oplog window combined with high write throughput
- Any CRITICAL or WARNING section with zero existing recommendations
- Prioritise by potential impact: data loss risk > performance > storage waste

Rules:
- Do NOT repeat any recommendation already in existing_recommendations
- Every recommendation must cite specific observed signal values as evidence
- "collection" field: use "db.collection" format for collection-level issues,
  or "cluster" for server-wide configuration issues
- "action" field: be specific and actionable — MongoDB shell commands, config parameter
  names, or clear investigation steps
- "confidence" field: always set to "llm"
- Output ONLY a valid JSON array — no explanation text, no markdown fences

Output schema:
[
  {
    "priority": "high | medium | low",
    "collection": "string",
    "action": "string",
    "evidence": "string — cite specific signal values from the report",
    "confidence": "llm"
  }
]

If there are no additional recommendations, output exactly: []
"""

# ── report serialiser ──────────────────────────────────────────────────────────

def _report_to_prompt_json(report: HealthCheckReport) -> str:
    """Serialise report to compact JSON for the LLM prompt.

    Strips verbose per-collection findings lines; keeps signal values and
    the first 4 non-empty finding lines per section so the prompt stays concise.
    """
    sections = []
    for s in report.sections:
        key_findings = [f.strip() for f in s.findings if f.strip()][:4]
        sections.append({
            "name": s.name,
            "severity": s.severity.value,
            "signals": [sig.to_dict() for sig in s.signals],
            "key_findings": key_findings,
        })

    existing = [
        {
            "priority": r.priority,
            "collection": r.collection,
            "action": r.action,
        }
        for r in report.recommendations
    ]

    return json.dumps({
        "cluster_uri": report.cluster_uri,
        "overall_severity": report.overall_severity.value,
        "sections": sections,
        "existing_recommendations": existing,
    }, indent=2, default=str)


# ── response parser ────────────────────────────────────────────────────────────

_VALID_PRIORITIES = {"high", "medium", "low"}


def _parse_llm_response(raw: str) -> List[Recommendation]:
    """Extract a JSON array from the LLM response and parse into Recommendation objects.

    Handles:
    - Responses wrapped in markdown code fences (```json ... ```)
    - Extra text before/after the JSON array
    - Missing or invalid fields (skipped gracefully)
    """
    text = raw.strip()

    # Strip markdown fences if present
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    text = text.strip()

    # Find the outermost JSON array
    match = re.search(r"\[.*\]", text, re.DOTALL)
    if not match:
        logger.warning("LLM response contained no JSON array — raw: %.200s", text)
        return []

    try:
        items = json.loads(match.group())
    except json.JSONDecodeError as exc:
        logger.warning("LLM JSON parse error: %s — raw: %.200s", exc, text)
        return []

    recs: List[Recommendation] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        priority = str(item.get("priority", "low")).lower().strip()
        if priority not in _VALID_PRIORITIES:
            priority = "low"
        collection = str(item.get("collection", "cluster")).strip()
        action     = str(item.get("action",     "")).strip()
        evidence   = str(item.get("evidence",   "")).strip()
        if not action:
            continue  # skip empty / malformed entries
        recs.append(Recommendation(
            priority=priority,
            collection=collection,
            action=action,
            evidence=evidence,
            confidence="llm",
        ))
    return recs


# ── public class ───────────────────────────────────────────────────────────────

class LLMRecommender:
    """Enriches rule-based health check recommendations with LLM cross-section reasoning."""

    def __init__(self, config: "AppConfig"):
        from utils.llm_factory import build_llm
        self._llm = build_llm(config)

    def enrich(self, report: HealthCheckReport) -> List[Recommendation]:
        """Return report.recommendations + any new LLM-generated ones.

        The report must already have rule-based recommendations attached
        (health_check_runner calls _build_recommendations first, then this).

        On any failure returns report.recommendations unchanged — LLM enrichment
        is best-effort and must never break the health check pipeline.
        """
        try:
            summary = _report_to_prompt_json(report)
            prompt  = f"{_SYSTEM_PROMPT}\n\nHealth Check Report:\n{summary}"
            raw     = self._llm.invoke(prompt)
            new_recs = _parse_llm_response(raw)
            if new_recs:
                logger.info("LLM enrichment produced %d additional recommendation(s)", len(new_recs))
            else:
                logger.info("LLM enrichment: no additional recommendations")
            return report.recommendations + new_recs
        except Exception as exc:
            logger.warning("LLM recommendation enrichment failed (non-fatal): %s", exc)
            return report.recommendations
